# frozen_string_literal: true

source "https://rubygems.org"

# frozen_string_literal: true

source "https://rubygems.org"

gem "sinatra", "~> 2.1"

ruby '2.7.0'

gem 'bcrypt', '~> 3.1', '>= 3.1.18'

gem "thin", "~> 1.8"

gem "rack-contrib", "~> 2.3"

gem "activerecord", "~> 6.1"


gem 'sinatra-activerecord'

gem 'faker'

gem "sqlite3", "~> 1.4"

gem "rake"

gem "rack-cors", "~> 1.1"

gem 'puma', '~> 6.1', '>= 6.1.1'

gem "require_all", "~> 3.0"

group :development do
    gem "pry", "~> 0.14.1"
    gem "rerun"
end


# gem "rails"


# gem "rails"
